config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  # scope "(:locale)", locale:/en|ar/ do
  scope "(:locale)", locale:/#{I18n.available_locales.join("|")}/ do

  resources :comments
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  resources :messages
  resources :users, param: :username
  resources :categories, param: :name
  
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :relationships,       only: [:create, :destroy]
  resources :follows,       only: [:create, :destroy]
  resources :categories
  resources :users do
    resources :messages
    member do
      get :following, :followers, :followersCat
    end
  end
  resources :categories do
     member do
      get :following
    end
  end

   resources :links, param: :title do
    collection do
      get 'search'
    end
      member do
        put "like", to:    "links#upvote"
        put "dislike", to: "links#downvote"
        put "notLogin", to:    "links#vote_notLogin"
        
      end
    resources :comments do
      member do
        put "like", to:    "comments#upvote"
        put "dislike", to: "comments#downvote"
      end
    end
  end
 
 # match "/404", :to => "errors#not_found"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root 'pages#welcome', as: 'home'
  # root :to => "pages#welcome"
  root 'links#index', as: 'home'
  root :to => "links#index"

   # example of regular Route.
  get 'about' => 'pages#about', as: 'about'
  get 'welcome' => 'pages#welcome', as: 'welcome'
  get '/signup', to: 'users#new' 
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

match "/404", :to => "errors#not_found", :via => :all
match "/500", :to => "errors#internal_server_error", :via => :all

  
end


# at the end of you routes.rb
# match '*a', :to => 'errors#routing', via: :get
# get '*unmatched_route', to: 'application#not_found'
 
end

app/views/shared/_add_link_model.html.erb
<!-- add link Model start -->
  <!-- Modal -->
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
          <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
          </button>
        </div>
        <div class="modal-body">
          <%= render 'links/fast_new_link'  %>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
          <button type="button" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    </div>
  </div>

  <!-- add link model end -->

app/views/shared/_category_row.html.erb
 <p id=""></p>

 <div class="card">
  <div class="container">
    <div class="row align-items-center" >
      <div class="col-1.5"> 
        <div class="thumbnail">
          <%= link_to  cl_image_tag(category.image_url ,class: "thumbnail" ), category if category.image? %>
          <%= link_to  image_tag('default-image-category.png',  class: "thumbnail "), category unless category.image? %>
        </div>
      </div>
      <div class="col-10.5">
        <P><b><h2>
         <div class="link_name">
           <% if I18n.locale == :ar  %>
           <%= link_to category.arabic_name, category   %>
           <% else %>
           <%= link_to category.name, category   %>
           <% end %>
         </div>
       </h2>
     </b></P>   
     <% if current_user?(category.user) %>
     <span class="delete_overflow">
      <%= link_to content_tag(:i,nil, class: 'fa fa-trash-o'), category, method: :delete, data: { confirm: 'Are you sure?' } %>

    </span>
    <% end %>
  </div>
</div>
<div class="w-100"></div>
<div class="row align-items-start" >
  <div class="col-1"> 
  </div>
  <div class="col-11">
    <p> 
      <h4>
        <%= category.about %>
      </h4>
    </p>
  </div>
</div>
<div class="w-100"></div>
<div class="row align-items-start" >
  <div class="col-12 my-2">
    <%= render 'categories/cat_follow_form',category: category if logged_in? %>
  </div>
</div>
</div>
</div>

app/views/shared/_comment_row.html.erb
 <p id=""></p>

 <% @a = "" %>
 <% @b = "" %>
 <% unless current_user.nil? %>
 <% if (current_user.voted_as_when_voted_for comment).nil? %> 
 <% @a = "" %>
 <% @b = "" %>
 <% elsif current_user.voted_as_when_voted_for comment %>
 <% @a =  "upvoted"   %>
 <% else %>  
 <% @b =  "downvoted"   %>
 <% end %>
 <% end %>

        <div class="card">
          <div class="container">
            <div class="row align-items-center " >
             <div class="col-12 my-4 mx-0">
              <table class=" table-unbordered " style="width: 100%;">
                <tbody>
                  <tr>
                    <th scope="row" class="text-sm-center align-middle"  width="5%" >
                      <% unless logged_in? %>
                      <%= link_to like_link_comment_path(link , comment), method: :put,:remote => true, class: "post_upvote"+@a do %>
                      <i class="fa fa-angle-up fa-2x" aria-hidden="true" ></i>
                      <% end %>
                      <% else %>
                      <%= link_to like_link_comment_path(link , comment), method: :put,:remote => true, class: "post_upvote"+@a do %>
                      <i class="fa fa-angle-up fa-2x" aria-hidden="true" ></i>
                      <% end %>
                      <% end %>
                    </th>
                    <td scope="row" rowspan="3" width="10%" class="align-middle">
                      <div style="max-width: 70px;" class="mx-1" >
                        <%= link_to  cl_image_tag(comment.user.image_url ,class: "card-img-top rounded-circle" ), link.user if comment.user.image? %>
                        <%= link_to  image_tag('default-image-link.png',  class: "thumbnail custom-img"), comment.user.url unless comment.user.image? %>
                      </div>

                    </td>
                    <td colspan="" rowspan="2">
                      <p class="card-text "> 
                        <div class="link_name">
                          <h5>
                            <b>
                              <%= comment.body %>
                            </b>
                          </h5>
                          
                        </div>

                      </p>
                      <hr class="my-1">
                    </td>
                  </tr>
                  <tr>
                    <th scope="row" class="text-sm-center align-middle">
                      <div class="post_points" id="score_<%= comment.id %>" title="<%= comment_score(comment) %>">
                        <%= number_to_human(comment_score(comment), :units => {:thousand => "K"},:format =>"%n%u",:precision => 4)  # => "500 K"
                        %>
                      </div>
                    </th>
                  </tr>
                  <tr>
                    <th scope="row" class="text-sm-center align-middle">
                    <% unless logged_in? %>
                     <%= link_to dislike_link_comment_path(link , comment), method: :put,:remote => true, class: "post_downvote"+@b do %>
                     <i class="fa fa-angle-down fa-2x" aria-hidden="true"></i>          
                     <% end %>
                     <% else %>
                     <%= link_to dislike_link_comment_path(link , comment), method: :put,:remote => true, class: "post_downvote"+@b do %>
                     <i class="fa fa-angle-down fa-2x" aria-hidden="true"></i>          
                     <% end %>
                     <% end %>
                    </th>

                    <td colspan="3" >
                    <div class="card-text small">
                      <ul class="list-inline">
                        <li class="list-inline-item">
                          <small ><%= t(:label_by) %>  
                            <%= link_to comment.user.username, comment.user %>
                          </small>
                        </li>
                        <li class="list-inline-item">
                          <small ><%= t(:label_ago) %>   
                            <%= time_ago_in_words(comment.created_at ) %>
                          </small>
                        </li>

                        <% if comment.user == current_user %>
                        <li class="list-inline-item">
                         <small >
                           <%= link_to  t(:label_delete) , comment, method: :delete, data: { confirm: 'Are you sure?' } %>
                         </small>
                       </li> 

                       <% else %>
                       <li class="list-inline-item">
                        <small><%= t(:label_report) %></small>
                      </li>
                      <% end %>
                    </ul>
                  </div>
                </td>

                  </tr>


                 
            </tbody>
          </table>
        </div>
      </div>

    </div>
  </div>  

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation" >
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %> 

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="microposts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_flash.html.erb
 
 <div class="alert alert-<%= type %>"><%= message %>
 	
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>

 	
 </div>
 

app/views/shared/_following_list_ar.html.erb
<div id="followingListId" class="following-list">

    <% @maxFollowList = 13 %>
    <% if !current_user.nil? %>
    <% @categories = current_user.cat_followed %>
    <% else %>
    <% @categories = Category.all %>
    <% end %>
    <nav id="following-list-navbar" class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr--6 " id="topMenuListId">

         <%= link_to_in_li '' , categories_path(), class: "nav-link nav-edit fa fa-pencil-square-o fa-1x edit-align" %>

         <%= link_to_in_li t(:label_popular)  ,links_path() , class: "nav-link" %>

         <% @categories.each_with_index  do |category, index| %>
         <% if index < @maxFollowList %>
         <%= link_to_in_li category.name ,category , class: "nav-link" %>
         <% end %>

         <% end %> 

         <% if @categories.length > @maxFollowList %>
         <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">More</a>
          <div class="dropdown-menu dropdown-menu-right">
            <% @categories.each_with_index  do |category, index| %>
            <% if index >= @maxFollowList %>
            <%= link_to category.name ,home_path(category: category.name) , class: "dropdown-item" %>
            <% end %>
            <% end %> 
           
          </div>
        </li>
        <% end %>
      </ul>

    </div>
  </nav>

</div>

app/views/shared/_following_list_en.html.erb
<div id="followingListId" class="following-list">

    <% @maxFollowList = 13 %>
    <% if !current_user.nil? %>
    <% @categories = current_user.cat_followed %>
    <% else %>
    <% @categories = Category.all %>
    <% end %>
    <nav id="following-list-navbar" class="navbar navbar-expand-lg navbar-dark bg-dark">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarText">
        <ul class="navbar-nav mr-auto " id="topMenuListId">

         <%= link_to_in_li '' , categories_path(), class: "nav-link nav-edit fa fa-pencil-square-o fa-1x edit-align" %>

         <%= link_to_in_li t(:label_popular)  ,links_path() , class: "nav-link" %>

         <% @categories.each_with_index  do |category, index| %>
         <% if index < @maxFollowList %>
         <%= link_to_in_li category.name ,category , class: "nav-link" %>
         <% end %>

         <% end %> 

         <% if @categories.length > @maxFollowList %>
         <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" data-toggle="dropdown" href="#" role="button" aria-haspopup="true" aria-expanded="false">More</a>
          <div class="dropdown-menu dropdown-menu-right">
            <% @categories.each_with_index  do |category, index| %>
            <% if index >= @maxFollowList %>
            <%= link_to category.name ,home_path(category: category.name) , class: "dropdown-item" %>
            <% end %>
            <% end %> 
           
          </div>
        </li>
        <% end %>
      </ul>

    </div>
  </nav>

</div>

app/views/shared/_link_row.html.erb
<p id=""></p>

<% @a = "" %>
<% @b = "" %>
<% unless current_user.nil? %>
<% if (current_user.voted_as_when_voted_for link).nil? %>
<% @a = "" %>
<% @b = "" %>
<% elsif current_user.voted_as_when_voted_for link %>
<% @a =  "upvoted"   %>
<% else %>  
<% @b =  "downvoted"   %>
<% end %>
<% end %>

<div class="card">
  <div class="media m-4">
   <div class="media-left mx-3">
     <div class="box">
      <div class="text-sm-center align-middle">
        <% unless logged_in? %>
        <%= link_to notLogin_link_path(link),method: :put, class: "post_upvote "+@a  do %>
        <i class="fa fa-caret-up fa-2x" aria-hidden="true"></i>
        <% end %>
        <% else %>
        <%= link_to like_link_path(link), method: :put,:remote => true, class: "post_upvote "+@a  do %>
        <i class="fa fa-caret-up fa-2x" aria-hidden="true"></i>
        <% end %>
        <% end %>
      </div>
       <div style="height: 20px;"></div>
      <div class="text-sm-center align-middle">
       <div class="post_points" title="<%= link_score(link) %>">
          <%= number_to_human(link_score(link), :units => {:thousand => "K"},:format =>"%n%u",:precision => 4)  # => "500 K"
          %>
        </div>
      </div>
      <div style="height: 20px;"></div>
      <div class="text-sm-center align-middle">
        <% unless logged_in? %>
        <%= link_to notLogin_link_path(link),method: :put, class: "post_downvote "+@a  do %>
        <i class="fa fa-caret-down fa-2x" aria-hidden="true"></i>
        <% end %>
        <% else %>
        <%= link_to dislike_link_path(link), method: :put,:remote => true, class: "post_downvote "+@b do %>
        <i class="fa fa-caret-down fa-2x" aria-hidden="true"></i>          
        <% end %>
        <% end %>
      </div>
    </div>
  </div>
  <div class="media-left">
    <%= link_to  cl_image_tag(link.image_url ,class: "thumbnail custom-img" ), link.url,class: "thumbnail custom-img" , target: :_blank if link.image? %>
  </div>
  <div class="media-body mt-4">
    <h4 class="media-heading"></h4>
    <div class="link_name">
      <h5>
        <b>
          <%= link_to link.title, link.url, class: "" , target: :_blank %>
        </b>
      </h5>
      <%= link_to URL_domain(link.url), 'https://'+URL_domain(link.url),:class =>"domain" , target: :_blank %>
      <hr class="my-1">
    </div>

    <div class="card-text small">
      <ul class="list-inline">
        <li class="list-inline-item">
          <small ><%= t(:label_by) %>  
            <%= link_to link.user.username, link.user %>
          </small>
        </li>
        <li class="list-inline-item">
          <small ><%= t(:label_ago) %>   
            <%= time_ago_in_words(link.created_at ) %>
          </small>
        </li>
        <li class="list-inline-item">
          <small ><%= t(:label_in) %>
            <%= link_to link.category.name, link.category %>
          </small>
        </li>

        <li class="list-inline-item">
          <small ><%= t(:label_in) %>
           <%= link_to link_comments(link) , link %>
         </small>
       </li>

       <% if link.user == current_user %>
       <li class="list-inline-item">
         <small >
           <%= link_to  t(:label_delete) , link, method: :delete, data: { confirm: 'Are you sure?' } %>
         </small>
       </li> 

       <% else %>
       <li class="list-inline-item">
        <small><%= t(:label_report) %></small>
      </li>
      <% end %>

    </ul>
  </div>
</div>
</div>
</div>


      

app/views/shared/_message_form.html.erb
<%= form_for(@message) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Send new message..." , cols: "30", rows: "10" %>
    
    <%= hidden_field_tag(:user_id, @user.id ) %>

  </div>
  <%= f.submit "Send", class: "btn btn-primary" %>
 	
<% end %>

<script type="text/javascript">
 
</script>

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats pull-left">
    <strong id="following" class="stat">
      <%= @category.follower.count %>
    </strong>
    متابع
</div>

app/views/shared/_user_info.html.erb
<% if logged_in? %>
<span><%= link_to gravatar_for(current_user, size: 100), current_user %></span>
<br></br>
<span><h1><%= current_user.name %></h1></span>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.messages.count, "messages") %></span>
<% else %>
<%= link_to gravatar_for(@user, size: 50), @user %>
<h1><%= @user.name %></h1>
<h1><%= @user.email %></h1>

<% end %>

app/views/shared/error_404.html.erb
.site
  .services-page 
    .error-template
      %h1
        Oops!
      %h2
        404 Not Found
      .error-details
        Sorry, an error has occured, Requested page not found!
        You tried to access '#{@not_found_path}', which is not a valid page.
      .error-actions
        %a.button_simple_orange.btn.btn-primary.btn-lg{href: root_path}
          %span.glyphicon.glyphicon-home
          Take Me Home