config/routes.rb
Rails.application.routes.draw do
  get 'errors/not_found'

  get 'errors/internal_server_error'

  # scope "(:locale)", locale:/en|ar/ do
  scope "(:locale)", locale:/#{I18n.available_locales.join("|")}/ do

  resources :comments
  get 'password_resets/new'

  get 'password_resets/edit'

  get 'sessions/new'

  resources :messages
  resources :users, param: :username
  resources :categories, param: :name
  
  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]
  resources :relationships,       only: [:create, :destroy]
  resources :follows,       only: [:create, :destroy]
  resources :categories
  resources :users do
    resources :messages
    member do
      get :following, :followers, :followersCat
    end
  end
  resources :categories do
     member do
      get :following
    end
  end

   resources :links, param: :title do
    collection do
      get 'search'
    end
      member do
        put "like", to:    "links#upvote"
        put "dislike", to: "links#downvote"
        put "notLogin", to:    "links#vote_notLogin"
        
      end
    resources :comments do
      member do
        put "like", to:    "comments#upvote"
        put "dislike", to: "comments#downvote"
      end
    end
  end
 
 # match "/404", :to => "errors#not_found"


  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  # root 'pages#welcome', as: 'home'
  # root :to => "pages#welcome"
  root 'links#index', as: 'home'
  root :to => "links#index"

   # example of regular Route.
  get 'about' => 'pages#about', as: 'about'
  get 'welcome' => 'pages#welcome', as: 'welcome'
  get '/signup', to: 'users#new' 
  post '/signup',  to: 'users#create'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'

match "/404", :to => "errors#not_found", :via => :all
match "/500", :to => "errors#internal_server_error", :via => :all

  
end


# at the end of you routes.rb
# match '*a', :to => 'errors#routing', via: :get
# get '*unmatched_route', to: 'application#not_found'
 
end

app/views/layouts/_header_ar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-between " >

  <%= link_to image_tag('favicon.ico',  class: "navbar-brand img-rounded logoImg") ,root_path %>
  <%= form_tag search_links_path, method: :get, class: "form-inline col-sm-5 ", role: "search" do %>
  
  <div class="input-group input-group-sm  ar_search_field">
    <%= text_field_tag :search, params[:search], class: "form-control input-group search_input ar_search_field_dir" , placeholder: "ابحث فى LinkO" %>
    <span class="input-group-btn ">
      <%= button_tag  ' ', name: nil, class: "btn btn-secondary " do %>
      <i class="fa fa-search" aria-hidden="true"></i>
      <% end %>
    </span>
  </div>
  <% end %>

  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
    <ul class="navbar-nav ">
      <li class="nav-item nav-item-custom">
        <%= link_to t(:label_addLink), new_link_path ,class: "btn btn-success custom-btn-sm mx-1"  %> 
      </li>
      <li class="nav-item ">
        <p>
         <%= link_to_in_li ' '+t(:label_home) , root_path , class: "nav-link fa fa-newspaper-o headerFont" %>     
       </p>

     </li>

     <li class="nav-item">
       <%= link_to_in_li ' '+t(:label_headerAbout) , about_path , class: "nav-link fa fa-question-circle headerFont" %>
     </li>

     <% if logged_in? %>
  <!--  <li class="nav-item">
    <%= link_to_in_li ' '+t(:label_headerNewLink), new_link_path , class: "nav-link fa  fa-link headerFont" %>
  </li> -->
     <!--  <li class="nav-item ">
       <%= link_to_in_li t(:label_headerNewCategory), new_category_path , class: "nav-link fa fa-th-list" %>
      </li>
    -->
    <% if current_user.admin %>
    <li class="nav-item">
     <%= link_to_in_li "Users", users_path , class: "nav-link" %>
   </li>
   <% end %>

   <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle fa fa-user headerFont" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <%= t(:label_headerAccount)  %>
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink" style="direction: ltr;">
      <%= link_to t(:label_space) + current_user.username.to_s, current_user , class: "dropdown-item fa fa-user headerFont dropdown-menu-right"  %>
      <%= link_to ' '+ t(:label_headerAccountEdit)+ ' ',  edit_user_path(current_user) , class: "dropdown-item fa fa-edit headerFont dropdown-menu-right"  %>
      <%= link_to t(:label_logout), logout_path, method: :delete , class: "dropdown-item fa fa-sign-out headerFont dropdown-menu-right"  %>
    </div>
  </li>
  

  <% else %>
  <li class="nav-item dropdown">
    <%= link_to ' '+t(:label_NewAccount), signup_path , class: "nav-link fa fa-user-plus headerFont"  %>
  </li>

  <li class="nav-item dropdown">
    <a href="javascript:;" class="dropdown-toggle nav-link fa fa-sign-in headerFont" data-toggle="dropdown"><b><%= ' '+t(:label_login) %></b>
     <span class="caret"></span></a>
     <ul id="login-dp" class="dropdown-menu dropdown-menu-left">
      <li>
       <%= render "layouts/navbar_login" %>
     </li>
   </ul>
 </li>

 <% end %>

 <li class="nav-item">
   <% if I18n.locale == :ar  %>
   <%= link_to_in_li ' '+t(:label_english),  { :locale=>'en' } , class: "nav-link fa fa-globe headerFont" %>
   <% else %>
   <%= link_to_in_li ' '+t(:label_arabic),  { :locale=>'ar' } , class: "nav-link fa fa-globe headerFont" %>
   <% end %>
 </li>
</ul>
</div>
</nav>

app/views/layouts/_header_en.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-between " style="background-color: #b92b27;">
  <%= link_to image_tag('favicon.ico',  class: "navbar-brand img-rounded logoImg") ,root_path %>
  <%= form_tag search_links_path, method: :get, class: "form-inline custom-search-form", role: "search" do %>
  <div class="input-group input-group-sm  ">
    <%= text_field_tag :search, params[:search], class: "form-control search_field" , placeholder: "Search LinkO" %>
    <span class="input-group-btn search_field">
      <%= button_tag  ' ', name: nil, class: "btn btn-secondary search_field" do %>
      <i class="fa fa-search search_field" aria-hidden="true"></i>
      <% end %>
    </span>
  </div> 
  
  <% end %> 
  
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse justify-content-end" id="navbarNavDropdown">
    <ul class="navbar-nav ">
      <li class="nav-item nav-item-custom">
          <%= link_to t(:label_addLink), new_link_path ,class: "btn btn-success custom-btn-sm mx-1"  %> 
      </li>
      <li class="nav-item ">
        <p>
         <%= link_to_in_li ' '+t(:label_home) , root_path , class: "nav-link fa fa-newspaper-o headerFont" %>
       </p>

     </li>

     <li class="nav-item">
       <%= link_to_in_li ' '+t(:label_headerAbout) , about_path , class: "nav-link fa fa-question-circle headerFont" %>
     </li>

     <% if logged_in? %>
  <!--  <li class="nav-item">
    <%= link_to_in_li ' '+t(:label_headerNewLink), new_link_path , class: "nav-link fa  fa-link headerFont" %>
  </li> -->
     <!--  <li class="nav-item ">
       <%= link_to_in_li t(:label_headerNewCategory), new_category_path , class: "nav-link fa fa-th-list" %>
      </li>
    -->
    <% if current_user.admin %>
    <li class="nav-item">
     <%= link_to_in_li "Users", users_path , class: "nav-link" %>
   </li>
   <% end %>

   <li class="nav-item dropdown ">
    <a class="nav-link dropdown-toggle fa fa-user headerFont" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
      <%= t(:label_headerAccount)  %>
    </a>
    <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
      <%= link_to ' '+current_user.username.to_s+ ' ', current_user , class: "dropdown-item fa fa-user headerFont"  %>
      <%= link_to t(:label_headerAccountEdit),  edit_user_path(current_user) , class: "dropdown-item fa fa-edit headerFont"  %>

      <%= link_to t(:label_logout), logout_path, method: :delete , class: "dropdown-item fa fa-sign-out headerFont"  %>
    </div>
  </li>
  <li class="nav-item ">

  </li>


  <% else %>
  <li class="nav-item dropdown">
    <%= link_to ' '+t(:label_NewAccount), signup_path , class: "nav-link fa fa-user-plus headerFont"  %>
  </li>

  <li class="nav-item dropdown">
    <a href="javascript:;" class="dropdown-toggle nav-link fa fa-sign-in headerFont" data-toggle="dropdown"><b><%= ' '+t(:label_login) %></b>
     <span class="caret"></span></a>
     <ul id="login-dp" class="dropdown-menu dropdown-menu-right">
      <li>
       <%= render "layouts/navbar_login" %>
     </li>
   </ul>
 </li>
 <% end %>

 <li class="nav-item">
   <% if I18n.locale == :ar  %>
   <%= link_to_in_li ' '+t(:label_english),  { :locale=>'en' } , class: "nav-link fa fa-globe headerFont" %>
   <% else %>
   <%= link_to_in_li ' '+t(:label_arabic),  { :locale=>'ar' } , class: "nav-link fa fa-globe headerFont" %>
   <% end %>
 </li>
</ul>



</div>
</nav>

app/views/layouts/_navbar_login.html.erb
<div class="row">
  <div class="col-md-12">
    Login via
    <div class="social-buttons">
      <a href="javascript:;" class="btn btn-fb"><i class="fa fa-facebook"></i> Facebook</a>
      <a href="javascript:;" class="btn btn-tw"><i class="fa fa-twitter"></i> Twitter</a>
    </div>
                    or
     <!-- <form class="form" role="form" method="post" action="login" accept-charset="UTF-8" id="login-nav"> -->
      <%= form_for(:session, url: login_path) do |f| %>
        <div class="form-group">
          <label class="sr-only" for="exampleInputEmail2">Email address</label>
          <%= f.email_field :email, class: 'form-control',placeholder: 'Email address', type: 'email', required: '',id: 'exampleInputEmail2' %>
        </div>
        <div class="form-group">
          <label class="sr-only" for="exampleInputPassword2">Password</label>
          <%= f.password_field :password, class: 'form-control',placeholder: 'Password', type: 'password', required: '',id: 'exampleInputPassword2' %>
             <div class="help-block text-right">
              <%= link_to "Forget the password ?", new_password_reset_path %>
            </div>
        </div>
        
        
        <div class="form-group">
           <button type="submit" class="btn btn-primary btn-block">Sign in</button>
        </div>
        <div>
          <%= f.label :remember_me, class: "checkbox" do %>
          <%= f.check_box :remember_me %>
          <span>keep me logged-in </span>
        <% end %>
        </div>

     <!-- </form> -->
     <% end %>  
  </div>
  <div class="bottom text-center">
    New here ? 
     <b><%= link_to "Join Us", signup_path   %></b>
    
  </div>
</div>

app/views/layouts/_navigation_links.html.erb
<% if current_page?(locale: :ar)  %>
	<%= content_tag :li do %>
	<%= link_to 'Switch to English', locale: :en %>
		
	<% end  %>
		<% else %>
	<%= content_tag :li do %>
		<%= link_to 'Switch to ar', locale: :ar %>
	<% end %>	
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head >
  <title><%= full_title(yield(:title)) %></title>
  <meta charset="utf-8">

  <link rel="shortcut icon" type="image/png" href="/assets/images/linkO-logo.png">
  <%= favicon_link_tag %>
  <%= csrf_meta_tags %>
  <%= stylesheet_link_tag "application_#{I18n.locale}", media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <div class="header">
    <% if I18n.locale == :ar  %>
    <%= render "layouts/header_ar" %>
    <% else %>
    <%= render "layouts/header_en" %>
    <% end %>

  </div>
</head>
<body>
 <% if I18n.locale == :ar  %>
 <%= render 'shared/following_list_ar'  %>
 <% else %>
 <%= render 'shared/following_list_en'  %>
 <% end %>
 
 <br>
 <div class="container">
   <%= render_flash %>
 </div>
 <%= yield %>

 <%= debug(params) if Rails.env.development? %> 

</body>
</html>

<script type="text/javascript">
  $(document).ready(function() {
  // $("#topMenuListId  li").on('click', function(e) {
  //     alert('change has been made');


  // });
  // if ($('#topMenuListId li').length > 10) {
  //   $('#dropdownMenu2').show();
  // }
  // else
  // {
  //  $('#dropdownMenu2').hide(); 
  // }
  $('#topMenuListId li').each(function (i) {

    var index = $(this).index();
    var text = $(this).text();
    var value = $(this).attr('value');
        // alert('Index is: ' + index + ' and text is ' + text + ' and Value ' + value);
      }); 

});

</script>